apiVersion: v1
kind: Service
metadata:
  name: sms-app-service
  namespace: sms
  labels:
    app: sms-app
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080
  selector:
    app: sms-app
