apiVersion: v1
kind: Secret
metadata:
  name: sms-db-secret
  namespace: sms
type: Opaque
data:
  # base64-encoded values
  # admin123 -> YWRtaW4xMjM=
  # studentdb -> c3R1ZGVudGRi
  POSTGRES_PASSWORD: YWRtaW4xMjM=
  POSTGRES_DB: c3R1ZGVudGRi
